insert into movie (name, year, genre_id) values ('The Shawshank Redemption' , 1994, 1);
insert into movie (name, year, genre_id) values ('The Godfather' , 1972, 1);
insert into movie (name, year, genre_id) values ('The Godfather: Part II' , 1974, 1);
insert into movie (name, year, genre_id) values ('The Dark Knight' , 2008, 1);
insert into movie (name, year, genre_id) values ('12 Angry Men' , 1957, 1);
insert into movie (name, year, genre_id) values ('The Lord of the Rings: The Return of the King' , 2003, 1);
insert into movie (name, year, genre_id) values ('Pulp Fiction' , 1994, 1);
insert into movie (name, year, genre_id) values ('The Good, the Bad and the Ugly' , 1966, 1);
insert into movie (name, year, genre_id) values ('Fight Club' , 1999, 1);
insert into movie (name, year, genre_id) values ('The Lord of the Rings: The Fellowship of the Ring' , 2001, 1);
insert into movie (name, year, genre_id) values ('Forrest Gump' , 1994, 1);
insert into movie (name, year, genre_id) values ('Inception' , 2010, 1);
insert into movie (name, year, genre_id) values ('Star Wars: Episode V - The Empire Strikes Back' , 1980, 1);
insert into movie (name, year, genre_id) values ('The Lord of the Rings: The Two Towers' , 2002, 1);
insert into movie (name, year, genre_id) values ('Joker' , 2019, 1);
insert into movie (name, year, genre_id) values ('The Matrix' , 1999, 1);
insert into movie (name, year, genre_id) values ('Goodfellas' , 1990, 1);
insert into movie (name, year, genre_id) values ('Seven Samurai' , 1954, 1);
insert into movie (name, year, genre_id) values ('Se7en' , 1995, 1);