version: '3'

networks:
  new:

services:
  redis:
    image: redis
    networks:
      - new
    ports:
      - "6379:6379"
  zipkin:
    image: openzipkin/zipkin
    networks:
      - new
    ports:
      - "9411:9411"
  eureka-server:
    image: ms-pattern-impl/eureka-server
    networks:
      - new
    ports:
      - "8761:8761"
  microservice-movie-genres:
    image: ms-pattern-impl/movie-genres
    networks:
      - new
    ports:
      - "8081:8081"
  microservice-movie:
    image: ms-pattern-impl/movie
    networks:
      - new
    ports:
      - "8082:8082"