insert into GENRE (description) values ('Absurdist');
insert into GENRE (description) values ('Action');
insert into GENRE (description) values ('Adventure');
insert into GENRE (description) values ('Comedy');
insert into GENRE (description) values ('Crime');
insert into GENRE (description) values ('Drama');
insert into GENRE (description) values ('Fantasy');
insert into GENRE (description) values ('Historical');
insert into GENRE (description) values ('Historical fiction');
insert into GENRE (description) values ('Horror');
insert into GENRE (description) values ('Magical realism');
insert into GENRE (description) values ('Mystery');
insert into GENRE (description) values ('Paranoid fiction');
insert into GENRE (description) values ('Philosophical');
insert into GENRE (description) values ('Political');
insert into GENRE (description) values ('Romance');
insert into GENRE (description) values ('Saga');
insert into GENRE (description) values ('Satire');
insert into GENRE (description) values ('Science fiction');
insert into GENRE (description) values ('Social');
insert into GENRE (description) values ('Speculative');
insert into GENRE (description) values ('Thriller');
insert into GENRE (description) values ('Urban');
insert into GENRE (description) values ('Western');